### ISSUE TITLE
Tracebacks running code

### ISSUE THREAD

**Issue by jrojasUNC** [elide-b/starbars#6] opened 2024-08-05 21:22 UTC
I pip installed (pip install starbars) but example code in https://pypi.org/project/starbars/1.3.0/ and this repo throw tracebacks.

example in https://pypi.org/project/starbars/1.3.0/:
![image](https://github.com/user-attachments/assets/512c171d-2205-4291-8f64-cd18b174929a)

example in https://github.com/elide-b/starbars/blob/cd987a90ca8c537de540eba73d89867132bbc6bf/examples/hue.py:
![image](https://github.com/user-attachments/assets/fc04e5d6-d876-4a7e-ad56-52cca3d7a5d3)

**Comment by Helveg** [comment] 2024-08-06 18:26
Hi there! I'd like to help you!. Could you please post the full command and entirety of the output (build logs, error logs, ...) as pure text [formatted code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)?

Could you also give tell me which version of Python, IPython and Jupyter notebook you're using? This might be a duplicate of https://github.com/elide-b/starbars/issues/5, where versions of `seaborn` under `0.13.0` don't work.

**Closed** 2024-08-19 00:07 UTC
